"""Idea 4: warm-start the weight policy from the situation grid, then adapt.

    python3 scripts/fit_policy_to_grid.py --grid situation_demands_qc.json
    python3 scripts/fit_policy_to_grid.py ... --eval        # + frozen laps, needs acados

The learner's problem so far has been its signal: TD on the controller's own
cost points a fixed direction (TODO 2w), and the fitted critic's direction
comes from white theta-noise that the horizon mostly averages away (2s). But
there is a learning signal already on disk that is neither: the situation
grid (2y) drove every (q_v, k_v, q_c) vector in every (sector, entry-speed)
cell and kept the winner. That is a measured target for what the weights
should be in each situation.

So: fit the policy network to the grid FIRST -- supervised, no noise, no
critic -- and let online learning start from a network that is already a
function of the situation. The fit uses the same machinery the tuner uses
(``WeightPolicy.step`` forward, ``WeightPolicy.grads`` backward), on
sequences of features generated by walking the track at each grid speed, so
the recurrent cell sees inputs in the order it will see them when driving.

The output box is DATA-DRIVEN: the grid's winners span q_v 0.2-2.0 and
q_c 0.1-1.0, far outside the factor-2 adaptation box. The box is drawn to
contain every target with a factor-1.5 margin, intersected with the global
limits. Online adaptation then happens inside a box that the grid says is
worth exploring, rather than one drawn around a single anchor.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

os.environ.setdefault("OMP_NUM_THREADS", "1")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from mpcc_tuning import baselines as B  # noqa: E402
from mpcc_tuning.ltc import (LTCCell, N_FEATURES, THETA_HI, THETA_LO,  # noqa: E402
                             WeightPolicy, features)
from mpcc_tuning.mpcc import WEIGHT_NAMES  # noqa: E402
from mpcc_tuning.track import Track  # noqa: E402

RES, FIG = ROOT / "results", ROOT / "paper" / "figures"
INK, MUT, GRID = "#212529", "#868E96", "#DEE2E6"
SEC_COL = ("#4C6EF5", "#0CA678", "#E8590C", "#AE3EC9")
SEC_NAME = ("straight", "long curve", "90-deg", "180-deg")
IDX = {n: i for i, n in enumerate(WEIGHT_NAMES)}


def targets_from_grid(path, track_name):
    """{(sector, v0): log-theta target (8,)} with non-grid weights at START."""
    d = json.loads(Path(path).read_text())
    s = d["summary"][track_name]
    th0 = np.asarray(B.start(track_name).theta(), float)
    out, speeds = {}, set()
    for k, bv in s["best_vec"].items():
        sec, v0 = k.split("|"); sec, v0 = int(sec), float(v0)
        th = th0.copy()
        th[IDX["q_v"]] = np.log(bv[0]); th[IDX["k_v"]] = np.log(bv[1])
        if len(bv) > 2 and bv[2] > 0:
            th[IDX["q_c"]] = np.log(bv[2])
        out[(sec, v0)] = th; speeds.add(v0)
    return out, sorted(speeds), d.get("config", {})


def data_box(targets, th0, margin=1.5):
    T = np.vstack(list(targets.values()) + [th0])
    lo = np.maximum(T.min(0) - np.log(margin), np.asarray(THETA_LO, float))
    hi = np.minimum(T.max(0) + np.log(margin), np.asarray(THETA_HI, float))
    # theta_0 must be strictly interior for the policy's squash to have span
    lo = np.minimum(lo, th0 - 0.05); hi = np.maximum(hi, th0 + 0.05)
    return lo, hi


def walk(track, v, ds=0.10):
    """Features along one lap at constant speed v, in driving order, with the
    sector the grid would label each point with."""
    feats, secs = [], []
    for s in np.arange(0.0, track.length, ds):
        p = np.asarray(track.pos(s), float).ravel()[:2]
        psi = float(track.tangent_angle(s))
        s5 = np.array([p[0], p[1], psi, v, s])
        feats.append(features(track, s5)); secs.append(int(track.sector(s)))
    return np.asarray(feats), np.asarray(secs)


def ridge_readout(pol, walks, targets, speeds, ridge=1e-2, t_max=0.95):
    """Closed-form fit of the readout G: the squash is invertible, the readout
    is linear in the hidden state, so z_target = atanh((theta - theta0)/span)
    and G = ridge-regression of z_target on h over the whole walk.

    The cell is left as it is -- a fixed nonlinear filter of the features
    (reservoir style). SGD through the recurrence was measured to plateau at
    RMSE ~0.30 in log space and never capture the 10x q_v swing between the
    two entry speeds; a linear solve captures whatever the hidden state
    carries, exactly, in one step.
    """
    H, Z = [], []
    for v in speeds:
        X, S = walks[v]; pol.reset()
        for x, sec in zip(X, S):
            pol.step(x)
            tgt = targets.get((int(sec), float(v)))
            if tgt is None:
                continue
            dev = tgt - pol.theta0
            span = np.where(dev >= 0.0, pol.hi - pol.theta0, pol.theta0 - pol.lo)
            t = np.clip(dev / np.maximum(span, 1e-9), -t_max, t_max)
            H.append(pol._u.copy()); Z.append(np.arctanh(t))
    H, Z = np.asarray(H), np.asarray(Z)
    A = H.T @ H + ridge * np.eye(H.shape[1])
    pol.G[...] = np.linalg.solve(A, H.T @ Z).T
    return H, Z


def fit(track_name, grid_path, epochs=60, lr=2e-2, seed=0, hidden=12, verbose=True,
        readout="ridge"):
    track = getattr(Track, track_name)()
    targets, speeds, cfg = targets_from_grid(grid_path, track_name)
    th0 = np.asarray(B.start(track_name).theta(), float)
    lo, hi = data_box(targets, th0)
    pol = WeightPolicy(LTCCell(N_FEATURES, hidden, seed=seed), th0, lo, hi, seed=seed)
    walks = {v: walk(track, v) for v in speeds}
    rng = np.random.default_rng(seed)
    hist = []
    if readout == "ridge":
        ridge_readout(pol, walks, targets, speeds)
        se = 0.0; n = 0
        for v in speeds:
            X, S = walks[v]; pol.reset()
            for x, sec in zip(X, S):
                th = pol.step(x); tgt = targets.get((int(sec), float(v)))
                if tgt is not None:
                    se += float((th - tgt) @ (th - tgt)); n += 1
        hist.append(np.sqrt(se / max(n, 1)))
        if verbose:
            print(f"  ridge readout  rmse(log theta) {hist[-1]:.4f}", flush=True)
    for ep in range(epochs):
        se = 0.0; n = 0
        for v in rng.permutation(speeds):
            X, S = walks[v]
            pol.reset()
            # start at a random point of the lap so the recurrent state does
            # not always warm up on the same stretch
            roll = rng.integers(len(X))
            X, S = np.roll(X, -roll, axis=0), np.roll(S, -roll)
            for x, sec in zip(X, S):
                th = pol.step(x)
                tgt = targets.get((int(sec), float(v)))
                if tgt is None:
                    continue
                err = th - tgt                      # log space
                dG, dc = pol.grads(2.0 * err)       # d(sum err^2)/dtheta chained through the policy
                g = np.sqrt((dG ** 2).sum() + (dc ** 2).sum())
                f = min(1.0, 1.0 / max(g, 1e-9))    # clip the step, not the direction
                pol.G -= lr * f * dG
                pol.cell.p -= lr * f * dc
                pol.cell.clip()
                se += float(err @ err); n += 1
        rmse = np.sqrt(se / max(n, 1))
        hist.append(rmse)
        if verbose and (ep % 10 == 0 or ep == epochs - 1):
            print(f"  epoch {ep:3d}  rmse(log theta) {rmse:.4f}", flush=True)
    return pol, targets, speeds, lo, hi, np.array(hist), walks


def report(pol, targets, speeds, walks, lo, hi, th0, track_name, out_png):
    """Per-cell fitted vs target, and a figure of the fitted policy around the lap."""
    print("\n  fitted policy vs grid target, per cell (values, not logs):")
    print("  %-11s %4s | %-22s | %-22s" % ("sector", "v0", "target q_v k_v q_c", "fitted  q_v k_v q_c"))
    fig, axes = plt.subplots(len(speeds), 1, figsize=(11, 3.2 * len(speeds)), squeeze=False)
    fig.patch.set_facecolor("white")
    for ax, v in zip(axes[:, 0], speeds):
        X, S = walks[v]; pol.reset()
        TH = np.array([pol.step(x) for x in X]); s_grid = np.arange(0, len(X)) * 0.10
        start = 0
        for i in range(1, len(S) + 1):
            if i == len(S) or S[i] != S[start]:
                ax.axvspan(s_grid[start], s_grid[min(i, len(S) - 1)], color=SEC_COL[S[start]], alpha=0.12, lw=0); start = i
        for name, c in (("q_v", "#0CA678"), ("q_c", "#4C6EF5"), ("k_v", "#E8590C")):
            i = IDX[name]
            ax.plot(s_grid, np.exp(TH[:, i]), color=c, lw=1.8, label=f"{name} fitted")
            tg = np.array([np.exp(targets[(int(s), float(v))][i]) if (int(s), float(v)) in targets else np.nan for s in S])
            ax.plot(s_grid, tg, color=c, lw=1.0, ls="--", alpha=0.8)
        ax.set_yscale("log"); ax.set_title(f"entry speed {v:.0f} m/s -- solid = network, dashed = grid target",
                                          loc="left", fontsize=10, fontweight="bold", color=INK)
        ax.set_ylabel("weight", color=MUT); ax.grid(True, color=GRID, lw=0.6); ax.set_axisbelow(True)
        for sp in ("top", "right"): ax.spines[sp].set_visible(False)
        ax.legend(frameon=False, fontsize=8, ncol=3, loc="upper right")
        for sec in sorted(set(S.tolist())):
            m = S == sec
            fitted = np.exp(TH[m].mean(0)); tgt = np.exp(targets[(sec, float(v))])
            print("  %-11s %4.1f | %5.2f %5.2f %5.2f        | %5.2f %5.2f %5.2f"
                  % (SEC_NAME[sec], v, tgt[IDX["q_v"]], tgt[IDX["k_v"]], tgt[IDX["q_c"]],
                     fitted[IDX["q_v"]], fitted[IDX["k_v"]], fitted[IDX["q_c"]]))
    axes[-1, 0].set_xlabel("arc length s (m)", color=MUT)
    fig.suptitle(f"{track_name}: weight policy fitted to the situation grid (idea 4)", fontsize=11, color=INK, x=0.01, ha="left")
    fig.savefig(out_png, dpi=170, bbox_inches="tight", facecolor="white"); plt.close(fig)
    print("  wrote", out_png)


def frozen_eval(pol, lo, hi, track_name, seeds=(0, 1, 2)):
    from mpcc_tuning.acados_mpcc import AcadosMPCC
    from experiments.online_from_baseline import run_frozen
    t = getattr(Track, track_name)(); st = B.start(track_name)
    m = AcadosMPCC(t, horizon=st.horizon, dt=0.05, vehicle="dynamic", q_vref=st.q_vref, name=f"fitgrid_{track_name}")
    out = []
    for seed in seeds:
        s0 = (seed % 4) * t.length / 4.0; v0 = 1.0 + 0.1 * (seed % 3)
        laps, off = run_frozen(m, pol, t, s0, v0, st.steps, features)
        out.append((seed, laps, off))
        print("  frozen fitted policy, seed %d: %.2f laps %s" % (seed, laps, "OFF" if off else "clean"), flush=True)
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--track", default="icra_t2_raceline")
    ap.add_argument("--grid", default="situation_demands_qc.json", help="file under results/")
    ap.add_argument("--epochs", type=int, default=0,
                    help="SGD fine-tuning epochs after the ridge readout (0 = none)")
    ap.add_argument("--readout", choices=("ridge", "sgd"), default="ridge")
    ap.add_argument("--lr", type=float, default=2e-2)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--eval", action="store_true", help="drive the fitted network frozen on 3 starts (needs acados)")
    ap.add_argument("--out", default=None)
    a = ap.parse_args(argv)
    th0 = np.asarray(B.start(a.track).theta(), float)
    pol, targets, speeds, lo, hi, hist, walks = fit(a.track, RES / a.grid, a.epochs, a.lr, a.seed,
                                                    readout=a.readout)
    print("\n  data-driven box (values):")
    for i, n in enumerate(WEIGHT_NAMES):
        print("    %-6s %7.3f .. %7.3f   (theta_0 %.3f)" % (n, np.exp(lo[i]), np.exp(hi[i]), np.exp(th0[i])))
    report(pol, targets, speeds, walks, lo, hi, th0, a.track, FIG / f"fitted_policy_{a.track}.png")
    out = Path(a.out) if a.out else RES / f"fitted_policy_{a.track}.npz"
    np.savez(str(out), G=pol.G, cell_p=pol.cell.p, lo=lo, hi=hi, th0=th0, rmse=hist,
             grid=str(a.grid), seed=a.seed)
    print("  wrote", out)
    if a.eval:
        frozen_eval(pol, lo, hi, a.track)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
