"""Hand-written pgfplots/TikZ versions of the paper race-learning figures.

Emits standalone-compilable .tex (documentclass=standalone + pgfplots) into
results/race/paper/tikz/, plus the .dat tables the trajectory figure reads. Pure vector
pgfplots (no raster), so they drop straight into an IEEE paper -- lift the tikzpicture, or
\\input the file. Reuses the SAME data as tools/paper_race_learning.py (reward5 JSON +
the cached frozen-net state logs results/race/paper/states_ltc_<seed>_<kind>.npz).

    PYTHONPATH=...:. python3 tools/paper_race_tikz.py [--seed 0] [--kinds equal faster]

(run tools/paper_race_learning.py first so the state-log caches exist.)
"""
import sys, argparse
from pathlib import Path
import numpy as np
ROOT = Path("/home/poxx/github/mpcc-online-tuning"); sys.path.insert(0, str(ROOT))
from mpcc_tuning.mpcc import WEIGHT_NAMES
from mpcc_tuning.track import Track
import tools.paper_race_learning as P

TZ = ROOT / "results/race/paper/tikz"; TZ.mkdir(parents=True, exist_ok=True)
KINDS, KCOL, KEY = P.KINDS, P.KCOL, P.KEY
# TikZ math labels (no $...$; pgfplots adds math in ticklabels via {$...$})
TLAB = {"q_c": r"q_c", "q_l": r"q_\ell", "q_v": r"q_v", "r_d": r"r_\delta", "r_a": r"r_a",
        "r_dv": r"r_{\dot v}", "d_obs": r"d_\mathrm{obs}", "k_v": r"k_v", "d_bound": r"d_\mathrm{bnd}"}


def hex2rgb(h):
    h = h.lstrip("#"); return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def colordefs():
    out = []
    for k in KINDS:
        r, g, b = hex2rgb(KCOL[k]); out.append(rf"\definecolor{{c{k}}}{{RGB}}{{{r},{g},{b}}}")
    return "\n".join(out)


HEADER = r"""% Auto-generated by tools/paper_race_tikz.py -- lift the tikzpicture into your IEEE paper,
% or compile this file directly (pdflatex/lualatex). Needs pgfplots >= 1.16.
\documentclass[tikz,border=2pt]{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepgfplotslibrary{groupplots,colormaps}
%%COLORS%%
\begin{document}
"""
FOOTER = "\n\\end{document}\n"


def write(name, body):
    txt = HEADER.replace("%%COLORS%%", colordefs()) + body + FOOTER
    (TZ / f"{name}.tex").write_text(txt)
    print(f"  wrote tikz/{name}.tex")


# --------------------------------------------------------------------------- 1) by opponent (heatmap)
_RDBU = np.array([(33, 102, 172), (103, 169, 207), (209, 229, 240), (247, 247, 247),
                  (253, 219, 199), (239, 138, 98), (178, 24, 43)], float)   # blue(-) -> white(0) -> red(+)


def _rdbu(t):
    """t in [-1,1] -> (r,g,b) 0-255 int, diverging RdBu (red = positive)."""
    t = float(np.clip(t, -1, 1)); x = (t + 1) / 2 * (len(_RDBU) - 1)
    i = int(np.floor(x)); f = x - i
    c = _RDBU[i] if i >= len(_RDBU) - 1 else _RDBU[i] * (1 - f) + _RDBU[i + 1] * f
    return tuple(int(round(v)) for v in c)


def tikz_by_opponent(runs):
    """Heatmap drawn with plain \\fill rectangles (colours precomputed) -- compiles anywhere."""
    M, start = P.weights_by_kind(runs)
    ks = [k for k in KINDS if k in M]
    Z = np.array([np.log2(M[k] / start) for k in ks])              # (nk, 9)
    vmax = float(np.nanmax(np.abs(Z))) or 1.0
    nk, nw = Z.shape
    cells = []
    for i in range(nk):                        # row i drawn at y = nk-1-i (static on top)
        yy = nk - 1 - i
        for j in range(nw):
            r, g, b = _rdbu(Z[i, j] / vmax)
            fg = "black" if abs(Z[i, j]) < 0.6 * vmax else "white"
            cells.append(rf"\fill[rgb color={{{r},{g},{b}}}] ({j},{yy}) rectangle ({j+1},{yy+1});")
            cells.append(rf"\node[font=\tiny, {fg}] at ({j+0.5},{yy+0.5}) {{{Z[i,j]:+.1f}}};")
    xt = "\n".join(rf"\node[font=\small] at ({j+0.5},-0.35) {{${TLAB[w]}$}};"
                   for j, w in enumerate(WEIGHT_NAMES))
    yt = "\n".join(rf"\node[font=\small, anchor=east] at (-0.15,{nk-1-i+0.5}) {{{ks[i]}}};"
                   for i in range(nk))
    # discrete colourbar (7 swatches) to the right
    cb_x = nw + 0.5; sw = []
    for s in range(7):
        r, g, b = tuple(int(round(v)) for v in _RDBU[s])
        sw.append(rf"\fill[rgb color={{{r},{g},{b}}}] ({cb_x},{s*nk/7:.3f}) rectangle ({cb_x+0.4},{(s+1)*nk/7:.3f});")
    body = rf"""\begin{{tikzpicture}}[rgb color/.style={{/utils/exec={{\definecolor{{tmpc}}{{RGB}}{{#1}}}}, draw=tmpc, fill=tmpc}}, x=0.62cm, y=0.62cm]
{chr(10).join(cells)}
{xt}
{yt}
{chr(10).join(sw)}
\node[font=\tiny, anchor=west] at ({cb_x+0.45},{nk}) {{$+{vmax:.1f}$}};
\node[font=\tiny, anchor=west] at ({cb_x+0.45},0) {{$-{vmax:.1f}$}};
\node[font=\footnotesize, anchor=south, rotate=90] at ({cb_x+1.15},{nk/2}) {{$\log_2(\mathrm{{emitted}}/\mathrm{{START}})$}};
\node[font=\small, anchor=south] at ({nw/2},{nk+0.15}) {{Learned weights by opponent class}};
\end{{tikzpicture}}"""
    write("fig_learn_by_opponent", body)


# --------------------------------------------------------------------------- 2) over rounds (groupplot)
def tikz_over_rounds(runs):
    C, start = P.curve_over_encounters(runs)
    idx = {w: WEIGHT_NAMES.index(w) for w in KEY}
    plots = []
    for gi, w in enumerate(KEY):
        j = idx[w]
        series = []
        for k in KINDS:
            mean, _ = C[k]
            if not len(mean):
                continue
            y = mean[:, j] / start[j]
            coords = " ".join(f"({e+1},{y[e]:.4f})" for e in range(len(y)) if np.isfinite(y[e]))
            series.append(rf"\addplot[color=c{k}, mark=*, mark size=1.2pt, line width=0.8pt] coordinates {{{coords}}};")
        legend = ""
        if gi == len(KEY) - 1:
            legend = r"\legend{" + ",".join(KINDS) + "}"
        plots.append(rf"""\nextgroupplot[title={{${TLAB[w]}$}}, xtick={{1,2,3,4}}]
\addplot[black, dashed, line width=0.4pt, domain=1:4] {{1}};
{chr(10).join(series)}
{legend}""")
    body = rf"""\begin{{tikzpicture}}
\begin{{groupplot}}[
  group style={{group size={len(KEY)} by 1, horizontal sep=0.9cm}},
  width=4.0cm, height=3.4cm, xlabel={{encounter $n$}},
  ylabel style={{font=\footnotesize}}, title style={{font=\small}},
  tick label style={{font=\scriptsize}}, grid=both, grid style={{gray!15}},
  legend style={{font=\scriptsize, draw=none, at={{(1.02,1)}}, anchor=north west}},
  every axis y label/.style={{at={{(-0.28,0.5)}}, rotate=90}},
]
"""
    # set y-label only on the first panel
    plots[0] = plots[0].replace("[title=", "[ylabel={emitted / START}, title=", 1)
    body += "\n".join(plots)
    body += "\n\\end{groupplot}\n\\end{tikzpicture}"
    write("fig_learn_over_rounds", body)


# --------------------------------------------------------------------------- 3) state traces (groupplot)
def tikz_state_traces(seed, kinds):
    logs = {k: P.get_states(seed, k, False) for k in kinds}
    def coords(k, key, fn=lambda a: a, ds=4):
        sl = P.one_lap(logs[k]["S"]); s = logs[k]["S"][sl]; y = fn(logs[k][key][sl])
        return " ".join(f"({s[i]:.3f},{y[i]:.4f})" for i in range(0, len(s), ds))
    def block(key, fn, ylabel, first=False):
        head = rf"\nextgroupplot[ylabel={{{ylabel}}}]" if not first else \
               rf"\nextgroupplot[ylabel={{{ylabel}}}, title={{our states along the lap}}]"
        lines = "\n".join(
            rf"\addplot[color=c{k}, line width=0.7pt] coordinates {{{coords(k, key, fn)}}};" for k in kinds)
        return head + "\n" + lines
    deg = lambda a: np.degrees(a)
    b0 = block("V", lambda a: a, r"$v$ [m/s]", first=True)
    b1 = block("BETA", deg, r"$\beta$ [deg]")
    b2 = block("R", deg, r"$\dot\psi$ [deg/s]") + "\n" + r"\legend{" + ",".join(kinds) + "}"
    body = rf"""\begin{{tikzpicture}}
\begin{{groupplot}}[
  group style={{group size=1 by 3, vertical sep=0.45cm,
    xlabels at=edge bottom, xticklabels at=edge bottom}},
  width=8.0cm, height=2.6cm, xlabel={{lap distance $s$ [m]}},
  tick label style={{font=\scriptsize}}, ylabel style={{font=\footnotesize}},
  title style={{font=\small}}, grid=both, grid style={{gray!15}},
  legend style={{font=\scriptsize, draw=none, at={{(1.02,1)}}, anchor=north west}},
]
{b0}
{b1}
{b2}
\end{{groupplot}}
\end{{tikzpicture}}"""
    write("fig_track_states_traces", body)


# --------------------------------------------------------------------------- 4) track + trajectory (vector)
def corridor_edges(n=900):
    d0 = np.load(ROOT / "mpcc_tuning/tracks/icra_t2_raceline_ref_corridor.npz")
    tt = Track(d0["cx"], d0["cy"], ds=0.1, w_left=d0["wl"], w_right=d0["wr"])
    ss = np.linspace(0, tt.length, n, endpoint=False); L = []; Rr = []
    for si in ss:
        p = np.asarray(tt.pos(float(si))).ravel(); a = float(tt.tangent_angle(float(si)))
        nx, ny = -np.sin(a), np.cos(a); wl, wr = tt.width(float(si))
        L.append([p[0] + nx * float(wr), p[1] + ny * float(wr)])
        Rr.append([p[0] - nx * float(wl), p[1] - ny * float(wl)])
    return np.array(L), np.array(Rr)


def tikz_track_traj(seed, kinds):
    L, Rr = corridor_edges()
    edge = lambda A: " ".join(f"({x:.3f},{y:.3f})" for x, y in A)
    vall = np.concatenate([P.get_states(seed, k, False)["V"] for k in kinds])
    vmin, vmax = float(vall.min()), float(vall.max())
    panels = []
    for k in kinds:
        Lg = P.get_states(seed, k, False); ex, ey, v = Lg["EX"], Lg["EY"], Lg["V"]
        # trajectory table (downsampled) -> its own .dat
        ds = 3; tbl = "x y v\n" + "\n".join(f"{ex[i]:.4f} {ey[i]:.4f} {v[i]:.4f}" for i in range(0, len(ex), ds))
        (TZ / f"traj_ltc_{seed}_{k}.dat").write_text(tbl)
        pas = np.asarray(Lg["PASS"]); jumps = np.where(np.diff(pas) > 0)[0] + 1
        passmark = ""
        if len(jumps):
            pc = " ".join(f"({ex[j]:.3f},{ey[j]:.3f})" for j in jumps)
            passmark = rf"\addplot[only marks, mark=star, mark size=2.6pt, color=cfaster] coordinates {{{pc}}};"
        panels.append(rf"""\nextgroupplot[title={{vs {k} opponent}}]
\addplot[gray!70, line width=0.5pt] coordinates {{{edge(L)}}};
\addplot[gray!70, line width=0.5pt] coordinates {{{edge(Rr)}}};
\addplot[mesh, point meta=explicit, line width=1.3pt] table[x=x,y=y,meta=v] {{traj_ltc_{seed}_{k}.dat}};
{passmark}""")
    body = rf"""\begin{{tikzpicture}}
\begin{{groupplot}}[
  group style={{group size={len(kinds)} by 1, horizontal sep=0.5cm}},
  width=6.0cm, height=6.0cm, axis equal image, hide axis,
  colormap/viridis, point meta min={vmin:.3f}, point meta max={vmax:.3f},
  title style={{font=\small}},
]
{chr(10).join(panels)}
\end{{groupplot}}
\begin{{axis}}[hide axis, scale only axis, height=0pt, width=0pt,
  colormap/viridis, colorbar horizontal, point meta min={vmin:.3f}, point meta max={vmax:.3f},
  colorbar style={{width=5cm, xlabel={{ego speed [m/s]}}, xlabel style={{font=\footnotesize}}, at={{(0.5,-0.12)}}, anchor=north}}]
\addplot[draw=none] coordinates {{(0,0)}};
\end{{axis}}
\end{{tikzpicture}}"""
    write("fig_track_traj", body)


def tikz_race_states(seed, kind):
    """Ego vs opponent states through a race (speeds, gap, our slip+yaw) vs time, pass marked."""
    L0 = P.get_states(seed, kind, False)
    sl = P.race_window(L0); L = {k: v[sl] if hasattr(v, "__len__") and len(v) == len(L0["V"]) else v for k, v in L0.items()}
    n = len(L["V"]); t = np.arange(n) * 0.05
    pas = np.asarray(L["PASS"]); jumps = np.where(np.diff(pas) > 0)[0] + 1
    tpass = t[jumps[0]] if len(jumps) else None
    ds = 3
    def C(y):
        return " ".join(f"({t[i]:.3f},{y[i]:.4f})" for i in range(0, n, ds))
    def vline(vals):
        if tpass is None:
            return ""
        lo, hi = float(np.min(vals)), float(np.max(vals)); pad = 0.08 * (hi - lo + 1e-9)
        return rf"\addplot[cfaster, line width=0.8pt, forget plot] coordinates {{({tpass:.3f},{lo-pad:.3f}) ({tpass:.3f},{hi+pad:.3f})}};"
    v_all = np.concatenate([L["V"], L["OV"]])
    p1 = rf"""\nextgroupplot[ylabel={{$v$ [m/s]}}, title={{ego vs {kind} opponent}},
  legend style={{at={{(0.5,1.35)}}, anchor=south, draw=none, font=\scriptsize}}, legend columns=2]
{vline(v_all)}
\addplot[color=c{kind}, line width=0.9pt] coordinates {{{C(L['V'])}}};
\addlegendentry{{ego}}
\addplot[color=gray, dashed, line width=0.9pt] coordinates {{{C(L['OV'])}}};
\addlegendentry{{opponent}}"""
    p2 = rf"""\nextgroupplot[ylabel={{gap [m]}}]
{vline(L['GAP'])}
\addplot[black, dotted, line width=0.4pt, forget plot] coordinates {{({t[0]:.2f},0) ({t[-1]:.2f},0)}};
\addplot[color=c{kind}, line width=0.9pt] coordinates {{{C(L['GAP'])}}};"""
    beta = np.degrees(L["BETA"]); yaw = np.degrees(L["R"]) / 10.0
    p3 = rf"""\nextgroupplot[ylabel={{$\beta$ [deg], $\dot\psi/10$}}, xlabel={{time [s]}},
  legend style={{at={{(0.98,0.95)}}, anchor=north east, draw=none, font=\scriptsize}}, legend columns=2]
{vline(np.concatenate([beta, yaw]))}
\addplot[color=c{kind}, line width=0.8pt] coordinates {{{C(beta)}}};
\addlegendentry{{$\beta$}}
\addplot[color=cslower, line width=0.8pt] coordinates {{{C(yaw)}}};
\addlegendentry{{$\dot\psi/10$}}"""
    body = rf"""\begin{{tikzpicture}}
\begin{{groupplot}}[
  group style={{group size=1 by 3, vertical sep=0.5cm,
    xlabels at=edge bottom, xticklabels at=edge bottom}},
  width=8.0cm, height=2.6cm, tick label style={{font=\scriptsize}},
  ylabel style={{font=\footnotesize}}, title style={{font=\small}},
  grid=both, grid style={{gray!15}},
]
{p1}
{p2}
{p3}
\end{{groupplot}}
\end{{tikzpicture}}"""
    write(f"fig_race_states_{kind}", body)


def write_readme(seed, kinds):
    txt = f"""# TikZ / pgfplots source for the race-mode paper figures

Auto-generated by `tools/paper_race_tikz.py` (seed {seed}, kinds {kinds}). Pure vector pgfplots.

Files:
- `fig_learn_by_opponent.tex`   heatmap: learned weights by opponent class (log2 vs START)
- `fig_learn_over_rounds.tex`   groupplot: key weights learning over episodes, per opponent class
- `fig_track_states_traces.tex` groupplot: our states v, beta, yaw-rate along the lap
- `fig_track_traj.tex` (+ `traj_ltc_{seed}_<kind>.dat`) track corridor + speed-coloured trajectory

Each .tex is a standalone document: `pdflatex fig_learn_over_rounds.tex` (or
`tectonic fig_learn_over_rounds.tex`) compiles it to a cropped PDF.

To include in the paper, put this in the preamble:

    \\usepackage{{pgfplots}}
    \\pgfplotsset{{compat=1.18}}
    \\usepgfplotslibrary{{groupplots,colormaps}}
    \\usepackage{{standalone}}          % makes \\input of these files work as-is

then `\\input{{tikz/fig_learn_over_rounds.tex}}` -- the standalone package turns the
\\documentclass/\\begin{{document}} wrapper into a no-op when included, so the same file
compiles standalone AND drops into the paper. (Or just lift the tikzpicture by hand.)

`fig_track_traj.tex` reads its `traj_*.dat` from the same folder (keep them together).
Matching PDFs (from matplotlib) are one level up in `results/race/paper/`.
"""
    (TZ / "README.md").write_text(txt)
    print("  wrote tikz/README.md")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--kinds", nargs="+", default=["equal", "faster"])
    ap.add_argument("--race-kinds", nargs="+", default=["slower", "equal"])
    a = ap.parse_args()
    runs, _ = P.load_runs("ltc")
    print("tikz ->", TZ)
    tikz_by_opponent(runs)
    tikz_over_rounds(runs)
    tikz_state_traces(a.seed, a.kinds)
    tikz_track_traj(a.seed, a.kinds)
    for rk in a.race_kinds:
        tikz_race_states(a.seed, rk)
    write_readme(a.seed, a.kinds)
